import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from backend.config import Config

class Notifier:
    """Handle external notifications (Email/Gmail)"""
    
    def __init__(self):
        self.smtp_server = Config.SMTP_SERVER
        self.smtp_port = Config.SMTP_PORT
        self.username = Config.SMTP_USERNAME
        self.password = Config.SMTP_PASSWORD
        self.target_email = Config.NOTIFICATION_EMAIL
        
        self.last_alert_time = None
        self.alert_cooldown = 300  # 5 minutes cooldown between automatic alerts
        
    def send_email_alert(self, risk_level, crowd_count, alerts, manual=False):
        """Send an email alert to authorities"""
        
        # Check cooldown for automatic alerts
        now = datetime.now()
        if not manual and self.last_alert_time:
            delta = (now - self.last_alert_time).total_seconds()
            if delta < self.alert_cooldown:
                print(f"Skipping automatic alert: Cooldown active ({int(delta)}s / {self.alert_cooldown}s)")
                return False
        
        if not self.username or not self.password or not self.target_email:
            print("Warning: SMTP configuration incomplete. Cannot send email.")
            return False
            
        try:
            # Create message
            msg = MIMEMultipart()
            msg['From'] = self.username
            msg['To'] = self.target_email
            
            subject_prefix = "[MANUAL ALERT]" if manual else "[CRITICAL ALERT]"
            msg['Subject'] = f"{subject_prefix} Crowd Stress Detected - Level: {risk_level}"
            
            # Create body
            alert_details = "\n".join([f"- {a['message']} (Action: {a['action']})" for a in alerts])
            
            body = f"""
AI-Driven Crowd Stress Detection System Alert
Timestamp: {now.strftime('%Y-%m-%d %H:%M:%S')}
Risk Level: {risk_level}
People Count: {crowd_count}

Active Alerts:
{alert_details if alerts else "No specific alert messages."}

This is an automated notification generated by the Crowd Detection System.
Please take appropriate action immediately.
"""
            msg.attach(MIMEText(body, 'plain'))
            
            # Connect and send
            print(f"Connecting to SMTP server {self.smtp_server}:{self.smtp_port}...")
            server = smtplib.SMTP(self.smtp_server, self.smtp_port)
            server.starttls()
            server.login(self.username, self.password)
            server.send_message(msg)
            server.quit()
            
            print(f"Email alert sent successfully to {self.target_email}")
            self.last_alert_time = now
            return True
            
        except Exception as e:
            print(f"Failed to send email alert: {str(e)}")
            return False

if __name__ == "__main__":
    # Test script
    notifier = Notifier()
    test_alerts = [{'message': 'Test alert message', 'action': 'No action needed'}]
    notifier.send_email_alert("TEST", 10, test_alerts, manual=True)
